### ISSUE TITLE
Image kubedb/es-operator:0.1.0 not found.

### ISSUE THREAD

**Issue by TamalSaha** [k8sdb/operator#58]
```
2017/06/01 19:43:52 registry.ping url=https://registry-1.docker.io/v2/
F0601 19:44:22.656522       1 run.go:75] Image kubedb/es-operator:0.1.0 not found.
goroutine 1 [running]:
github.com/k8sdb/operator/vendor/github.com/golang/glog.stacks(0xc420238400, 0xc4201ab810, 0x53, 0xa9)
	/home/tamal/go/src/github.com/k8sdb/operator/vendor/github.com/golang/glog/glog.go:766 +0xa7
github.com/k8sdb/operator/vendor/github.com/golang/glog.(*loggingT).output(0x29b03a0, 0xc400000003, 0xc4201ab760, 0x2906942, 0x6, 0x4b, 0x0)
	/home/tamal/go/src/github.com/k8sdb/operator/vendor/github.com/golang/glog/glog.go:717 +0x348
github.com/k8sdb/operator/vendor/github.com/golang/glog.(*loggingT).printDepth(0x29b03a0, 0x3, 0x2, 0xc4205b7a28, 0x1, 0x1)
	/home/tamal/go/src/github.com/k8sdb/operator/vendor/github.com/golang/glog/glog.go:646 +0x12d
github.com/k8sdb/operator/vendor/github.com/golang/glog.FatalDepth(0x2, 0xc4205b7a28, 0x1, 0x1)
	/home/tamal/go/src/github.com/k8sdb/operator/vendor/github.com/golang/glog/glog.go:1131 +0x5d
github.com/k8sdb/operator/vendor/github.com/appscode/log.doPrintf(0xc400000000, 0x1d2733d, 0x16, 0xc4205b7c08, 0x2, 0x2)
	/home/tamal/go/src/github.com/k8sdb/operator/vendor/github.com/appscode/log/log.go:136 +0x111
github.com/k8sdb/operator/vendor/github.com/appscode/log.Fatalf(0x1d2733d, 0x16, 0xc4205b7c08, 0x2, 0x2)
	/home/tamal/go/src/github.com/k8sdb/operator/vendor/github.com/appscode/log/log.go:29 +0x5b
main.run()
	/home/tamal/go/src/github.com/k8sdb/operator/run.go:75 +0xab8
main.NewCmdRun.func1(0xc42035bd40, 0xc4202742a0, 0x0, 0x2)
	/home/tamal/go/src/github.com/k8sdb/operator/run.go:46 +0x20
github.com/k8sdb/operator/vendor/github.com/spf13/cobra.(*Command).execute(0xc42035bd40, 0xc420274220, 0x2, 0x2, 0xc42035bd40, 0xc420274220)
	/home/tamal/go/src/github.com/k8sdb/operator/vendor/github.com/spf13/cobra/command.go:651 +0x23a
github.com/k8sdb/operator/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42035bb00, 0xc4205b7f60, 0xc42036cb40, 0xc42036cb40)
	/home/tamal/go/src/github.com/k8sdb/operator/vendor/github.com/spf13/cobra/command.go:726 +0x339
github.com/k8sdb/operator/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42035bb00, 0xc4205b7f58, 0x1)
	/home/tamal/go/src/github.com/k8sdb/operator/vendor/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/home/tamal/go/src/github.com/k8sdb/operator/main.go:27 +0x177
```

**Comment by aerokite** [comment]
Seems like `kubedb/es-operator:0.1.0` image is missing. 
Check this [issue](https://github.com/k8sdb/operator/issues/59#issuecomment-305680752)

**Comment by TamalSaha** [comment]
https://hub.docker.com/r/kubedb/es-operator/tags/ is there

**Comment by TamalSaha** [comment]
I think there was network issue on that node.
